//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDI_WINPX 1
#define IDS_WINPX 100
#define IDR_MENU_WINPX 100
#define IDS_OPTIONS_DIALOG 111
#define IDS_WELCOME_TITLE 112
#define IDS_WELCOME_MAIN_INSTRUCTION 113
#define IDS_WELCOME_CONTENT 114
#define IDS_WELCOME_CONTINUE 115
#define IDS_WELCOME_CUSTOMIZE 116
#define IDI_WINPX_DARK_NORMAL 131
#define IDI_WINPX_DARK_RUNNING 132
#define IDI_WINPX_DARK_PAUSED 133
#define IDI_WINPX_DARK_ERROR 134
#define IDI_WINPX_LIGHT_NORMAL 135
#define IDI_WINPX_LIGHT_RUNNING 136
#define IDI_WINPX_LIGHT_PAUSED 137
#define IDI_WINPX_LIGHT_ERROR 138
#define IDD_OPTIONS_GENERAL 201
#define IDD_OPTIONS_GATEWAY 202
#define IDD_OPTIONS_SECURITY 203
#define IDD_OPTIONS_STATUS 204
#define IDD_OPTIONS_DIAGNOSTICS 205
#define IDD_OPTIONS_ABOUT 206
#define IDC_GROUP_POLICY 1000
#define IDC_GENERAL_AUTO_START_APP 1100
#define IDC_GENERAL_AUTO_START_PROXY 1101
#define IDC_GENERAL_SET_ENVIRONMENT 1102
#define IDC_GENERAL_NETWORK_MODE 1103
#define IDC_GENERAL_PROXY_PORT 1104
#define IDC_GENERAL_WINPX_PROXY_URL 1105
#define IDC_GENERAL_COPY_PROXY_URL 1106
#define IDC_GENERAL_ADD_FIREWALL_RULE 1108
#define IDC_GATEWAY_USE_SYSTEM_PROXY 1200
#define IDC_GATEWAY_USE_AUTO_DETECT 1201
#define IDC_GATEWAY_USE_AUTO_CONFIG 1202
#define IDC_GATEWAY_USE_MANUAL_PROXY 1203
#define IDC_GATEWAY_NO_PROXY 1204
#define IDC_GATEWAY_AUTO_CONFIG_LABEL 1205
#define IDC_GATEWAY_AUTO_CONFIG_URL 1206
#define IDC_GATEWAY_HTTP_PROXY_LABEL 1207
#define IDC_GATEWAY_HTTP_PROXY_URL 1208
#define IDC_GATEWAY_HTTPS_PROXY_LABEL 1209
#define IDC_GATEWAY_HTTPS_PROXY_URL 1210
#define IDC_SECURITY_ALLOW_NEGOTIATE 1300
#define IDC_SECURITY_ALLOW_NTLM 1301
#define IDC_SECURITY_ALLOW_DIGEST 1302
#define IDC_SECURITY_ALLOW_BASIC 1303
#define IDC_SECURITY_USERNAME_LABEL 1304
#define IDC_SECURITY_USERNAME 1305
#define IDC_SECURITY_PASSWORD_LABEL 1306
#define IDC_SECURITY_PASSWORD 1307
#define IDC_SECURITY_REQUIRE_LOCAL_AUTH 1308
#define IDC_SECURITY_SECRET_LABEL 1309
#define IDC_SECURITY_SECRET 1310
#define IDC_SECURITY_REFRESH_SECRET 1311
#define IDC_STATUS_RESULT 1400
#define IDC_DIAGNOSTICS_URL 1500
#define IDC_DIAGNOSTICS_CHECK 1501
#define IDC_DIAGNOSTICS_RESULT 1502
#define IDC_ABOUT_VERSION 1600
#define IDC_ABOUT_LINK 1601
#define IDC_ABOUT_LICENSES 1602
#define ID_PROXY_START 32774
#define ID_PROXY_STOP 32775
#define ID_PROXY_OPTIONS 32776
#define ID_PROXY_EXIT 32777

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC 1
#define _APS_NEXT_RESOURCE_VALUE 207
#define _APS_NEXT_COMMAND_VALUE 32778
#define _APS_NEXT_CONTROL_VALUE 1604
#define _APS_NEXT_SYMED_VALUE 110
#endif
#endif
