<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <_PropertySheetDisplayName>Common</_PropertySheetDisplayName>
    <GitCommitHash Condition="'$(GitCommitHash)'==''">unknown</GitCommitHash>
  </PropertyGroup>
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <ItemDefinitionGroup>
    <ClCompile>
      <ConformanceMode>true</ConformanceMode>
      <ControlFlowGuard>Guard</ControlFlowGuard>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <PreprocessorDefinitions>GIT_COMMIT_HASH="$(GitCommitHash)";WIN32;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <SDLCheck>true</SDLCheck>
      <WarningLevel>Level4</WarningLevel>
    </ClCompile>
    <ResourceCompile>
      <PreprocessorDefinitions>GIT_COMMIT_HASH="$(GitCommitHash)";%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ResourceCompile>
    <Link>
      <ControlFlowGuard>Guard</ControlFlowGuard>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <DataExecutionPrevention>true</DataExecutionPrevention>
      <RandomizedBaseAddress>true</RandomizedBaseAddress>
    </Link>
  </ItemDefinitionGroup>
</Project>
